# arquivo para ci/cd AULA TI323 2026
name: CI/CD TI323

on: # como sera o gatilho
  push: # quando ocorrer um push
      branches: [ main ] # para a branch main
      paths: # para os arquivos
        - 'projeto/**' # para arquivos dentro da pasta projeto

jobs: # trabalho a ser realizado
  informacao_sistema:
    runs-on: ubuntu-latest
    steps: # passo a serem executados 
      - name: Lista o diretorio corrente
        run: ls -la

  compila-projeto:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projeto
    steps:
        - name: Checkout code
          uses: actions/checkout@v6
        - name: Lista para ver se os arquivos estão lá
          run: ls -Rla